#!/bin/bash
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/sbin
#get gw
	oldgw=`cat /tmp/vpn_oldgw`
	vpngw=`cat /tmp/vpn_vpngw`
source /usr/local/etc/dnsmasq/vpndown.sh
source /usr/local/etc/dnsmasq/ipdownadd.sh
#rm log
	rm -f /tmp/vpn_oldgw
	rm -f /tmp/vpn_vpngw
#clean dns cache
	dscacheutil -flushcache
	sudo killall -9 dnsmasq
